from __future__ import annotations

MEMORY_SCHEMA_VERSION = 3
MEMORY_KINDS = {"user_preference", "project_decision", "discussion_context"}

MAX_SCOPE_PATHS = 10
MAX_COMPACTION_CHARS = 4_000
MAX_SEARCH_RESULTS = 5
MAX_SEARCH_QUERY_CHARS = 256
MAX_SEARCH_QUERY_TOKENS = 16
MAX_CONTENT_TERMS = 256
MAX_CONTENT_TERM_CHARS = 160
MAX_RELATED_ITEMS = 20
MAX_READ_SOURCES = 3
MAX_SOURCE_EXCERPT_CHARS = 800
MAX_JOB_ERROR_CHARS = 20_000
MAX_MEMORY_STATEMENT_TOKENS = 320
MAX_REPETITION_EVIDENCE_TURNS = 20
MAX_REPETITION_EVIDENCE_TOKENS = 32 * 1024
MEMORY_STRENGTHS = {"hard", "soft"}
MEMORY_ORIGINS = {"explicit", "adopted_proposal", "inferred_repetition"}
MEMORY_RECALL_MODES = {"always", "on_match"}

EXTRACTION_BATCH_SIZE = 4
EXTRACTION_PENDING_THRESHOLD = 2
EXTRACTION_MAX_WAIT_SECONDS = 30
JOB_LEASE_SECONDS = 120
TURN_LEASE_SECONDS = 120
RETRY_BACKOFF_SECONDS = (5, 30, 120, 600, 3_600)
WORKER_POLL_SECONDS = 1.0

REPAIR_MEMORY_INTENTS = frozenset(
    {
        "code_audit",
        "patch_explain",
        "patch_revise",
    }
)
