from __future__ import annotations

from autopatch_j.core.domain import IntentType


MEMORY_VERSION = 1

MAX_EPISODES = 80
MAX_PENDING_EPISODE_IDS = 16
KEEP_EPISODES_AFTER_COMPACTION = 24
MAX_ACTIVE_TOPICS = 8
MAX_SEMANTIC_ITEMS = 50
MAX_PROCEDURAL_ITEMS = 30
MAX_SCOPE_PATHS = 10

MAX_USER_TEXT = 1000
MAX_ASSISTANT_TEXT = 2000
MAX_LABEL = 60
MAX_SUMMARY = 300
MAX_REPO_PROFILE_ITEMS = 20
MAX_REPO_PROFILE_TEXT = 120

MAX_PROMPT_PROCEDURAL_ITEMS = 5
MAX_PROMPT_SEMANTIC_ITEMS = 5
MAX_PROMPT_RELATED_EPISODES = 3
MAX_PROMPT_ACTIVE_TOPICS = 3
MAX_PROMPT_PENDING_INPUTS = 2

SOFT_FILE_BYTES = 64 * 1024
HARD_FILE_BYTES = 96 * 1024

ORDINARY_INTENTS = {IntentType.CODE_EXPLAIN, IntentType.GENERAL_CHAT}
