from __future__ import annotations

from autopatch_j.core.domain import IntentType


MEMORY_SCHEMA_VERSION = 2

ORDINARY_INTENTS = {IntentType.CODE_EXPLAIN, IntentType.GENERAL_CHAT}
MEMORY_KINDS = {"user_preference", "project_decision", "discussion_context"}

MAX_SCOPE_PATHS = 10
MAX_HISTORY_TURNS = 8
MAX_HISTORY_CHARS = 12_000
MAX_COMPACTION_CHARS = 4_000
MAX_ROUTING_CONTEXT_CHARS = 4_000
MAX_ROUTING_ITEM_CHARS = 400
MAX_SEARCH_RESULTS = 5
MAX_SEARCH_QUERY_CHARS = 256
MAX_SEARCH_QUERY_TOKENS = 16
MAX_CONTENT_TERMS = 256
MAX_CONTENT_TERM_CHARS = 160
MAX_RELATED_ITEMS = 20
MAX_READ_SOURCES = 3
MAX_SOURCE_EXCERPT_CHARS = 800
MAX_JOB_ERROR_CHARS = 20_000

EXTRACTION_BATCH_SIZE = 4
EXTRACTION_PENDING_THRESHOLD = 2
EXTRACTION_MAX_WAIT_SECONDS = 30
JOB_LEASE_SECONDS = 120
TURN_LEASE_SECONDS = 120
RETRY_BACKOFF_SECONDS = (5, 30, 120, 600, 3_600)
WORKER_POLL_SECONDS = 1.0
